io:
  logdir: logs/
  datadir: /tudelft.net/staff-bulk/ewi/insy/VisionLab/yanconglin/dataset/shapenet/shapenet-r2n2
  dataset: ShapeNet
  # datadir: /tudelft.net/staff-bulk/ewi/insy/VisionLab/yanconglin/dataset/new_pix3d
  # dataset: Pix3d
  resume_from: 
  num_workers: 2
  percentage: 0.01


model:
  batch_size: 5
  num_sym: 1

  H: 64
  W: 64
  C: 64
  
  lpos: 1.0
  lneg: 1.0
  
  D: 64
  depth_min: 0.64
  depth_max: 1.23
  
  n_levels: 3
  C_sphere: 1024
  theta:
    - 90.0  # deg
    - 12.856381599883887 # 128
    - 3.2771532030666553  # 64
    # - 0.8359901946121823 # 64
    
  num_nodes:
    - 128
    - 64
    - 64
    
  num_neighbors:
    - 16
    - 16
    - 16

  detection:
    enabled: true

optim:
  name: Adam
  max_epoch: 32
  lr_decay_epoch: [24]
  params:
    lr: 3.0e-4
    amsgrad: true
    weight_decay: 1.0e-7
